### ISSUE TITLE
Add user config: dynamic grid properties to upload

### ISSUE THREAD

**Issue by richypitman** [equinor/fmu-sumo-sim2sumo#154]
As a user, I would like to be able to specify the grid properties to upload to Sumo.

Currently, almost all static grid properties (except those that are "unwanted") are uploaded by `upload_init()`. Dynamic grid properties are uploaded by `upload_restart()`, which contains a tuple with some properties: `prop_names = ("SWAT", "SGAS", "SOIL", "PRESSURE", "SFIPOIL", "SFIPGAS").`

These properties could be used by default, or at least the first four in `prop_names`. I would like an option in the config to specify which dynamic properties are uploaded. For example:

```
sim2sumo:
  datatypes:
    - grid
  rstprops:
    - ["SWAT", "SGAS", "SOIL", "PRESSURE", "POT_CORR", "TEMP"]
```
