### ISSUE TITLE
Allow giving options per datafile

### ISSUE THREAD

**Issue by daniel-sol** [equinor/fmu-sumo-sim2sumo#57]
Users on Troll have requested feature to input options per datafile

**Comment by daniel-sol** [comment]
* datatypes as list, not only dictionary input
* read from more than model folders?

```
   datafiles:
    ix/model/TROLL_PRED_IX-1:
      summary:
        column_keys: '*'
    eclipse/migrator/TROLL_PRED_IX-1:
      pvt: 
        keywords: 
          - PVTO 
          - PVDG
    ix/include/ENS_NETWORK:
      vfp: 
        keywords:
          - VFPPROD
```
Comment on what is made: still reading rft file, but should just skip when it doesn't
