### ISSUE TITLE
Fails to return VFPINJ table upon user request

### ISSUE THREAD

**Issue by daniel-sol** [equinor/fmu-sumo-sim2sumo#76]
User input should extract tables with tagname VFPINJ as well as VFPPROD with user input:
```
yaml
 datatypes:
  vfp:
    keyword:
    - VFPPROD
    - VFPINJ
   ```
   in branch bugfix_vfping test data to reproduce the issue is added as `tests/data/oscar` with corresponding test file `tests/test_w_oscar.py`. Test uploads 9 tables with tagnames of the form VFPPROD_%d, and nothing else, but should upload one table with tagname `VPFINJ_1` as well
