### ISSUE TITLE
Revisit sim2sumo config setup

### ISSUE THREAD

**Issue by daniel-sol** [equinor/fmu-sumo-sim2sumo#79]
Go through valid config configurations, and start to formalize. 
Should end up in a pydantic model to help both users and improve code
Currently all these configurations are valid:

complete split of datafile, datatypes and options
````yaml
sim2sumo:
  datafile: eclipse/model/2_R001_REEK-0.DATA
  datatypes:
    - summary
    - grid
    - rft
  options:
    arrow: false
    time_index: daily,
    start_date: 2002-01-02
    end_date: 2003-01-02
````
Everthing as dictionary for granular control

````yaml
sim2sumo:
  datafile:
    2_R001_REEK-1.DATA:
      summary
      grid: true
    OOGRE.in:
      rft:
        wellname: ABC
        grid3d: true
      vfp:
        keyword:
          -VFPPROD
````
Datatypes as list
````yaml
sim2sumo:
  datatypes:
    - summary
    - grid
    - rft
````

And datatypes as dict to incorporate optional arguments

````yaml
 datatypes:
    summary:
         time_index: daily
    satfunc:
      keywords: SWOF
    rft:
      wellname: A1
````
