### ISSUE TITLE
Add number of columns and rows to metadata

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-sumo-sim2sumo#81]
As a user I would like to have the number of columns recorded in the metadata, so that I can more easily debug and quickly find realizations which have deviating number of columns.

Example:
FMU workflow produces `summary` files as large tables. For some realizations, the `summary` file contains less columns, for whatever reason. To find these deviations, I now have to identify all tables in the set and _download all the tables_, parse them to Pandas, then count the columns. This takes a LONG time.

Rather, if column length was included in the metadata (or rows), I could do this much more efficiently.

## Propose:
Put number of columns and rows into outgoing metadata as such:
```yaml
data:
  spec:
    size: 12345 # already there
    columns: ["ColA", "ColB", "ColN"] # already there (but sometimes stripped away)
    cols_count: 1000 # New!
    rows_count: 1000 # New!
```

(This is possibly an fmu-dataio issue?)
